import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import TaskMenu from "@/components/TaskMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "To Do app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <body className={inter.className}>
        <Header/>
        <TaskMenu/>
        {children}
        </body>
    </html>
  );
}
